from collections.abc import Awaitable, Sequence
from datetime import datetime
from typing import Protocol

from portal_contracts.media import (
    MediaAccepted,
    MediaCreate,
    MediaFileDelivery,
    MediaItemPage,
    MediaJobOut,
    MediaJobPage,
)
from src.modules.media.downloads.domain.dtos import (
    MediaItemChange,
    MediaJobChange,
)
from src.modules.media.downloads.domain.models import (
    MediaItemModel,
    MediaJobModel,
)
from src.modules.media.sources.domain.dtos import (
    DownloadPlan,
    MediaDownloadOutcome,
)


class IMediaJobService(Protocol):
    def record(
        self, id: int, lock: bool = False
    ) -> Awaitable[MediaJobModel]: ...
    def get(self, id: int, owner_id: int) -> Awaitable[MediaJobOut]: ...
    def create(
        self, data: MediaCreate, provider: str
    ) -> Awaitable[MediaAccepted]: ...
    def change(self, id: int, data: MediaJobChange) -> Awaitable[None]: ...
    def due(self, limit: int) -> Awaitable[Sequence[MediaJobModel]]: ...
    def expired(self, now: datetime) -> Awaitable[Sequence[MediaJobModel]]: ...
    def requeue_many(self, ids: Sequence[int]) -> Awaitable[None]: ...
    def dispatch_many(
        self, ids: Sequence[int], lease_until: datetime
    ) -> Awaitable[None]: ...
    def start_many(self, ids: Sequence[int]) -> Awaitable[None]: ...


class IMediaItemService(Protocol):
    def create_many(
        self, job_id: int, plan: DownloadPlan
    ) -> Awaitable[None]: ...
    def next(self, job_id: int) -> Awaitable[MediaItemModel | None]: ...
    def next_delivery(
        self, job_id: int
    ) -> Awaitable[MediaItemModel | None]: ...
    def ready(self, job_id: int) -> Awaitable[MediaItemModel | None]: ...
    def get(
        self, id: int, lock: bool = False
    ) -> Awaitable[MediaItemModel]: ...
    def change(self, id: int, data: MediaItemChange) -> Awaitable[None]: ...
    def interrupt(self, job_id: int) -> Awaitable[None]: ...
    def interrupt_many(self, ids: Sequence[int]) -> Awaitable[None]: ...
    def reserve_many(
        self, ids: Sequence[int], lease_until: datetime
    ) -> Awaitable[None]: ...
    def recover(self, now: datetime) -> Awaitable[None]: ...
    def save_many(self, rows: Sequence[MediaItemModel]) -> Awaitable[None]: ...


class IMediaCommands(Protocol):
    def accept(self, data: MediaCreate) -> Awaitable[MediaAccepted]: ...
    def cancel(self, id: int, owner_id: int) -> Awaitable[MediaJobOut]: ...


class IMediaQueries(Protocol):
    def page(
        self, owner_id: int, page: int, per_page: int
    ) -> Awaitable[MediaJobPage]: ...
    def items(
        self, id: int, owner_id: int, page: int, per_page: int
    ) -> Awaitable[MediaItemPage]: ...
    def authorize_file(self, data: MediaFileDelivery) -> Awaitable[bool]: ...


class IMediaPlanner(Protocol):
    def execute(self, job_id: int) -> Awaitable[None]: ...


class IMediaTransfer(Protocol):
    def execute(self, item_id: int) -> Awaitable[None]: ...


class IMediaTransferBatch(Protocol):
    def execute(self, item_ids: Sequence[int]) -> Awaitable[None]: ...


class IMediaDownloadRecorder(Protocol):
    def record(self, data: MediaDownloadOutcome) -> Awaitable[None]: ...


class IMediaDelivery(Protocol):
    def execute(self, job_id: int) -> Awaitable[None]: ...


class IMediaCompletion(Protocol):
    def refresh(self, job_id: int) -> Awaitable[None]: ...


class IMediaDispatch(Protocol):
    def dispatch(self) -> Awaitable[None]: ...


class IMediaQueue(Protocol):
    def dispatch(self) -> Awaitable[None]: ...
    def dispatch_at(self, when: datetime) -> Awaitable[None]: ...
    def plan_many(self, ids: Sequence[int]) -> Awaitable[None]: ...
    def transfer_many(self, ids: Sequence[int]) -> Awaitable[None]: ...
    def complete_many(self, ids: Sequence[int]) -> Awaitable[None]: ...
    def deliver_many(self, ids: Sequence[int]) -> Awaitable[None]: ...
    def downloaded(self, data: MediaDownloadOutcome) -> Awaitable[None]: ...


class IMediaMaintenance(Protocol):
    def recover(self) -> Awaitable[None]: ...
    def clean(self) -> Awaitable[None]: ...
