"""Create the Portal schema and editable business configuration."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "20261003_portal"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tbl_ai_budgets",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column(
            "reserved_usd", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "tbl_missions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("origin_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("origin_bot", sa.String(length=8), nullable=False),
        sa.Column("origin_message_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("actor", sa.String(length=8), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "lease_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("model_requests", sa.Integer(), nullable=False),
        sa.Column("tool_executions", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "update_id"),
    )
    op.create_index(
        "ix_missions_due", "tbl_missions", ["status", "id"], unique=False
    )
    op.create_index(
        "ix_missions_owner_status",
        "tbl_missions",
        ["owner_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_missions_owner_id"),
        "tbl_missions",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_missions_status"),
        "tbl_missions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "tbl_news_sources",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("feed_url", sa.String(length=2048), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "tbl_portal_guards",
        sa.Column("key", sa.String(length=96), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "tbl_setting_definitions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "tbl_agent_checkpoints",
        sa.Column("mission_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "history",
            sa.Text().with_variant(mysql.MEDIUMTEXT(), "mysql"),
            nullable=False,
        ),
        sa.Column("requests", sa.Integer(), nullable=False),
        sa.Column("tools", sa.Integer(), nullable=False),
        sa.Column("reactions", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["tbl_missions.id"],
        ),
        sa.PrimaryKeyConstraint("mission_id"),
    )
    op.create_table(
        "tbl_articles",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mission_id", sa.BigInteger(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["tbl_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id", "url_hash"),
    )
    op.create_index(
        op.f("ix_tbl_articles_mission_id"),
        "tbl_articles",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "tbl_llm_runs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mission_id", sa.BigInteger(), nullable=False),
        sa.Column("request_no", sa.Integer(), nullable=False),
        sa.Column("budget_day", sa.Date(), nullable=False),
        sa.Column(
            "reserved_usd", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column(
            "actual_usd", sa.Numeric(precision=18, scale=8), nullable=True
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["tbl_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id", "request_no"),
    )
    op.create_index(
        op.f("ix_tbl_llm_runs_mission_id"),
        "tbl_llm_runs",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "tbl_market_snapshots",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mission_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["tbl_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id"),
    )
    op.create_index(
        op.f("ix_tbl_market_snapshots_owner_id"),
        "tbl_market_snapshots",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "tbl_mission_events",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mission_id", sa.BigInteger(), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("detail", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["tbl_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tbl_mission_events_mission_id"),
        "tbl_mission_events",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "tbl_news_source_configs",
        sa.Column("source_id", sa.BigInteger(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["tbl_news_sources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_table(
        "tbl_private_replies",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("mission_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("origin_bot", sa.String(length=8), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "lease_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["tbl_missions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mission_id"),
    )
    op.create_index(
        "ix_private_replies_due",
        "tbl_private_replies",
        ["status", "scheduled_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_private_replies_status"),
        "tbl_private_replies",
        ["status"],
        unique=False,
    )
    op.create_table(
        "tbl_setting_values",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("definition_id", sa.BigInteger(), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["tbl_setting_definitions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("definition_id", "scope"),
    )
    op.create_table(
        "tbl_drafts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("origin_bot", sa.String(length=8), nullable=False),
        sa.Column("mission_id", sa.BigInteger(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=96), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("approved_revision", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("publisher_bot", sa.String(length=8), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("market_snapshot_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["market_snapshot_id"],
            ["tbl_market_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_tbl_drafts_owner_id"),
        "tbl_drafts",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_drafts_status"), "tbl_drafts", ["status"], unique=False
    )
    op.create_table(
        "tbl_draft_evidences",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("draft_id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["tbl_articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["tbl_drafts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("draft_id", "article_id"),
    )
    op.create_table(
        "tbl_publications",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=96), nullable=False),
        sa.Column("bot_role", sa.String(length=8), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("budget_day", sa.Date(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "lease_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["tbl_drafts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index(
        "ix_publications_budget",
        "tbl_publications",
        ["budget_day", "status"],
        unique=False,
    )
    op.create_index(
        "ix_publications_due",
        "tbl_publications",
        ["status", "scheduled_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_publications_owner_id"),
        "tbl_publications",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_publications_scheduled_at"),
        "tbl_publications",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tbl_publications_status"),
        "tbl_publications",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tbl_publications")
    op.drop_table("tbl_draft_evidences")
    op.drop_table("tbl_drafts")
    op.drop_table("tbl_setting_values")
    op.drop_table("tbl_private_replies")
    op.drop_table("tbl_news_source_configs")
    op.drop_table("tbl_mission_events")
    op.drop_table("tbl_market_snapshots")
    op.drop_table("tbl_llm_runs")
    op.drop_table("tbl_articles")
    op.drop_table("tbl_agent_checkpoints")
    op.drop_table("tbl_setting_definitions")
    op.drop_table("tbl_portal_guards")
    op.drop_table("tbl_news_sources")
    op.drop_table("tbl_missions")
    op.drop_table("tbl_ai_budgets")
    # ### end Alembic commands ###
